version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: edifiq-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/edifiq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - edifiq-network

  worker-distribution:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    container_name: edifiq-worker-distribution
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/edifiq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - edifiq-network

    deploy:
      replicas: 1

  mysql:
    image: mysql:8
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: edifiq-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edifiq
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - edifiq-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: edifiq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - edifiq-network

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  edifiq-network:
    driver: bridge
